version: '3.8'

services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DB_USER=admin
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_PASSWORD=abo333
      - DB_PORT=5432
      - PORT=8080
    command: sh -c "npm install && npm run migrate && npm start"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abo333
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
